FLAP_THRESHOLD = 0.2

POPULATION = 100

SURVIVORS = 10

# Randomizing
WEIGHT_SMALL_MUTATION_PROB = 0.8
WEIGHT_BIG_MUTATION_PROB = 0.2

# Neural network
INPUT_NEURONS = 5
HIDDENS = [5,4,3]
OUTPUT_NEURONS = 1
TOPOLOGY = [INPUT_NEURONS] + HIDDENS + [OUTPUT_NEURONS]
